### ISSUE TITLE
大数据量的benchmark

### ISSUE THREAD

**Issue by GreatStone** [JimChengLin/PiXiu#1]
我也曾经尝试做一个类似于Terark的引擎的东西，但是遇到的瓶颈就是构建速度，完全无法应用于在线场景，每秒1w+的写入kps和我之前构建的demo也差不多，但是在value极小而key数量增长到百万量级的时候，性能几乎无法接受，不知道PiXiu是否适应这种场景。
PS：PiXiu的README里面给出了一些开发上的Tips，不知道是否欢迎协同开发。

**Comment by JimChengLin** [comment]
我争取这几天做两个测试，第一就是gzip对比。第二就是大数据量对比。我觉得400MB的写入挺多的了。你要大量条数，小记录的测试吗？

**Comment by GreatStone** [comment]
我之前写的demo不是suffix tree而是DAWG，1G测试数据，单value大小1bit，key数量1500W，写入时间比较长。

**Comment by JimChengLin** [comment]
自动机技术不是很成熟了么？我当初看Terark最疑惑的就是DFA怎么做增量？于是我脑补出了这条用Suffix Tree的路。毫无疑问，1500W条打底就是1500W状态，肯定慢啊！我目前的方法其实还是传统的索引的路子，只不过我挂了一个Suffix Tree做压缩，然后用CritBit Tree抵消了压缩的副作用，综合看来效果还不错。我用的所有算法都是线性的，没啥必要测了你说的情况了。专栏有人问Gzip，我自己试了下。Gzip真的有点厉害，能压70-80%，跟PiXiu差不多了。但Gzip的数据没有全局性，会丢掉一些优化的空间，于是我把Gzip挂在后缀树压缩后的数据上，又小了50%。于是，有了gzpixiu编码。我最近人比较累。我一直不想做App开发，接下来有精力应该回去看看Linux和C++进阶。如果你要再开发，可以私信要我微信。我尽力帮哈。

**Comment by JimChengLin** [comment]
已正在写Benchmark
